# Generated by Django 3.0.1 on 2019-12-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('no', models.IntegerField()),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=35)),
            ],
        ),
    ]
